### ISSUE TITLE
Cannot open HADashboard

### ISSUE THREAD

**Issue by kajmaj** [hassio-addons/addon-appdaemon3#20]
Hello, 
I am using 
` Hass.io Add-on: AppDaemon v1.3.0
 Python Apps and HADashboard using AppDaemon 3.x for Home Assistant
 From: Community Hass.io Add-ons
 By: Franck Nijhof <frenck@addons.community>`
on Home Assistant 0.75.2 and HassOS 1.9
I edited dashboard and since that cannot open it at all.
Neither AppDaemon restart nor HomeAssistant reboot did not help.
Not even AppDaemon reinstall
There are several strange lines in the AppDaemon log:

`Traceback (most recent call last):
  File "/usr/bin/appdaemon", line 7, in <module>
    from appdaemon.admain import main
  File "/usr/lib/python3.6/site-packages/appdaemon/admain.py", line 2, in <module>
    from pkg_resources import parse_version
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 73, in <module>
    __import__('pkg_resources.extern.packaging.specifiers')
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 779, in get_code
  File "<frozen importlib._bootstrap_external>", line 487, in _compile_bytecode
ValueError: bad marshal data (unknown type code)`

Any idea how to recover functionality?

**Comment by frenck** [comment]
Please upgrade to HA 0.75.3

**Comment by kajmaj** [comment]
Thank you. Done, itś working now.
