### ISSUE TITLE
Upgraded to appdaemon3 now I can't get it to work

### ISSUE THREAD

**Issue by TeckPete** [hassio-addons/addon-appdaemon3#27]
# Problem/Motivation

> I upgraded to 3 and I cant get it to work, I thought I did all the right add and replace from https://appdaemon.readthedocs.io/en/latest/#upgrading-from-2-x , now Im getting more errors. Can I re-download or downgrade reset it? I'm at a loss trying to figure it out??

HA  0.80.0
appdaemon3 1.5.0

## Expected behavior

> (What you expected to happen)

## Actual behavior
LOG
**WAS GETTING THIS ERROR BE FOR I MADE THE CHANGES** 

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: AppDaemon v1.5.0
 Python Apps and HADashboard using AppDaemon 3.x for Home Assistant
 From: Community Hass.io Add-ons
 By: Franck Nijhof <frenck@addons.community>
-----------------------------------------------------------
 armhf / Resin OS 2.3.0+rev1 / HA 0.80.0 / SU 136 / stable
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 20-init-configuration.sh: executing... 
[cont-init.d] 20-init-configuration.sh: exited 0.
[cont-init.d] 21-compiled-dir.sh: executing... 
[cont-init.d] 21-compiled-dir.sh: exited 0.
[cont-init.d] 30-auto-password.sh: executing... 
[cont-init.d] 30-auto-password.sh: exited 0.
[cont-init.d] 31-ha-url.sh: executing... 
WARNING: You are using an non-recommended Home Assistant URL!
WARNING: Setting the "ha_url http://hassio/homeassistant" option in your AppDaemon config to
WARNING: "" is recommended!
[cont-init.d] 31-ha-url.sh: exited 0.
[cont-init.d] 50-compiled-symlink.sh: executing... 
[cont-init.d] 50-compiled-symlink.sh: exited 0.
[cont-init.d] 80-system-packages.sh: executing... 
[cont-init.d] 80-system-packages.sh: exited 0.
[cont-init.d] 81-python-packages.sh: executing... 
[cont-init.d] 81-python-packages.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
ERROR no 'appdaemon' section in /config/appdaemon/appdaemon.yaml
ERROR no 'appdaemon' section in /config/appdaemon/appdaemon.yaml
ERROR no 'appdaemon' section in /config/appdaemon/appdaemon.yaml
ERROR no 'appdaemon' section in /config/appdaemon/appdaemon.yaml

**NOW I'M GETTING THIS**

> data = constructor(self, node)
  File "/usr/lib/python3.6/site-packages/appdaemon/utils.py", line 101, in _secret_yaml
    raise ValueError("!secret used but no secrets file found")
ValueError: !secret used but no secrets file found
Traceback (most recent call last):
  File "/usr/bin/appdaemon", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/appdaemon/admain.py", line 375, in main
    admain.main()
  File "/usr/lib/python3.6/site-packages/appdaemon/admain.py", line 194, in main
    config = yaml.load(config_file_contents)
  File "/usr/lib/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 129, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/usr/lib/python3.6/site-packages/appdaemon/utils.py", line 101, in _secret_yaml
    raise ValueError("!secret used but no secrets file found")
ValueError: !secret used but no secrets file found
Traceback (most recent call last):
  File "/usr/bin/appdaemon", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/appdaemon/admain.py", line 375, in main
    admain.main()
  File "/usr/lib/python3.6/site-packages/appdaemon/admain.py", line 194, in main
    config = yaml.load(config_file_contents)
  File "/usr/lib/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 129, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/usr/lib/python3.6/site-packages/appdaemon/utils.py", line 101, in _secret_yaml
    raise ValueError("!secret used but no secrets file found")
ValueError: !secret used but no secrets file found
Traceback (most recent call last):
  File "/usr/bin/appdaemon", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/appdaemon/admain.py", line 375, in main
    admain.main()
  File "/usr/lib/python3.6/site-packages/appdaemon/admain.py", line 194, in main
    config = yaml.load(config_file_contents)
  File "/usr/lib/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 129, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/usr/lib/python3.6/site-packages/appdaemon/utils.py", line 101, in _secret_yaml
    raise ValueError("!secret used but no secrets file found")
ValueError: !secret used but no secrets file found
Traceback (most recent call last):
  File "/usr/bin/appdaemon", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/appdaemon/admain.py", line 375, in main
    admain.main()
  File "/usr/lib/python3.6/site-packages/appdaemon/admain.py", line 194, in main
    config = yaml.load(config_file_contents)
  File "/usr/lib/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 129, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/usr/lib/python3.6/site-packages/appdaemon/utils.py", line 101, in _secret_yaml
    raise ValueError("!secret used but no secrets file found")
ValueError: !secret used but no secrets file found
```

before and after screen shot

![app1](https://user-images.githubusercontent.com/35778227/46969227-a5203280-d072-11e8-8ac8-01ed1fed293a.JPG)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by AZDane** [comment]
I couldn't get mine to work either initially. I had a lot of API errors and changing the ha_url from an IP address to in my case ha_url: http://hassio.local:8123 fixed my problems.

**Comment by frenck** [comment]
@AZDane Incorrect URL. Please use `http://hassio/homeassistant` in `ha_url` and nothing else.

**Comment by AZDane** [comment]
Sorry about that. My initial thought was that since `http://hassio/homeassistant` doesn’t resolve to anything on my side it had to be dependent on how you installed hass.io. 
I'm new to Hass.io  and first now realized that the resolving happens internally in Hass.io
