### ISSUE TITLE
Cannot connect to 0.84.3

### ISSUE THREAD

**Issue by angel12** [hassio-addons/addon-appdaemon3#32]
# Problem/Motivation

> New install on HASS.IO with HASS 0.84.3, does not connect to home assistant

## Expected behavior

> Connect to Home Assistant

## Actual behavior

> errors in add-on log: 
2018-12-18 10:25:25.332573 INFO AppDaemon Version 3.0.2 starting
2018-12-18 10:25:25.333208 INFO Configuration read from: /config/appdaemon/appdaemon.yaml
2018-12-18 10:25:25.335767 INFO AppDaemon: Starting Apps
2018-12-18 10:25:25.343033 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2018-12-18 10:25:25.443029 INFO AppDaemon: HASS: HASS Plugin Initializing
2018-12-18 10:25:25.443995 INFO AppDaemon: HASS: HASS Plugin initialization complete
2018-12-18 10:25:25.444447 INFO Starting Dashboards
2018-12-18 10:25:25.454124 INFO API is disabled
2018-12-18 10:25:25.485412 WARNING AppDaemon: HASS: Disconnected from Home Assistant, retrying in 5 seconds

Errors in HASS log:
Error doing job: SSL handshake failed
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 609, in uvloop.loop.UVStream._on_eof
  File "uvloop/sslproto.pyx", line 171, in uvloop.loop._SSLPipe.feed_ssldata
  File "/usr/local/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:841)

Error doing job: SSL error errno:1 reason: TLSV1_ALERT_UNKNOWN_CA
Traceback (most recent call last):
  File "uvloop/sslproto.pyx", line 504, in uvloop.loop.SSLProtocol.data_received
  File "uvloop/sslproto.pyx", line 204, in uvloop.loop._SSLPipe.feed_ssldata
  File "uvloop/sslproto.pyx", line 171, in uvloop.loop._SSLPipe.feed_ssldata
  File "/usr/local/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:841)

## Steps to reproduce

> Start App Daemon Add-on inside Hass.io installation. I do have a custom URL with Duckdns as well as https through letsencrypt, and looking at the appdaemon.yaml in config/appdaemon, it is pointed to the correct url, but the cert_path is pointed to an old version of my cert, which isnt fixed when I try to replace that old cert (they are pointed to /config/appdaemon/fullchain.pem, instead of /ssl/fullchain.pem which I thought was standard for add ons?)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Weird, this should not happen. What URL do you use to connect to HA in your appdaemon configuration?
